#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

chesstra_program="$cmd_dir/chesstra"

echo "Running ChessTra"
$chesstra_program || panic "ChessTra program failed"

